language: node_js
cache: yarn
node_js:
  - 'stable'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
  - cd docs && yarn && cd ..
  - cd example && yarn && cd ..
script:
  - yarn run flow -- check
  - yarn run lint
deploy:
  provider: script
  script: docs/deploy.sh
  skip_cleanup: true
  on:
    branch: master
