language: node_js
cache: yarn
env:
  global:
    - ENCRYPTION_LABEL: "efa09eced906"
    - COMMIT_AUTHOR_EMAIL: "gh-bot@callstack.io"
node_js:
  - 'stable'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
  - cd docs && yarn && cd ..
  - cd example && yarn && cd ..
script:
  - yarn run flow -- check
  - yarn run lint
  - cd docs && bash ./deploy.sh
